### PR TITLE
Add an "all entries" option to the entry link modal

### PR DESCRIPTION
**Pull request by janhenckens**
This is a first stab at somewhat fixing #139, or at least making it usable for our client.

Hope this can be review quickly so we can use this when the site goes live.
Thanks!

### CODE REVIEW

**Comment by brandonkelly** [comment]
This was more of a Craft bug than Redactor. Just fixed at the source for the 3.2.0 release, due out on Tuesday.

**Comment by janhenckens** [comment]
Great! Thanks for the fast update :)

**Comment by janhenckens** [comment]
@brandonkelly This looks good but "All entries" would still be nice to have here. That way we can search across all sections when adding a link through this modal.

**Comment by cakleimeier** [comment]
Is there any chance of getting an "All Entries" tab in the Entries modal accessed via the "Link" button in Redactor? This would be a very helpful feature on large sites with lots of Entries.

**Comment by andris-sevcenko** [comment]
@cakleimeier It's tricky. Relational fields have it because they don't care whether the entries linked have URLs or not. Redactor absolutely should not be displaying entries that cannot be linked to.

However, there might some way of facilitating this. Can you post that as a new issue, please?

**Comment by cakleimeier** [comment]
@andris-sevcenko I've posted that issue as #228; thanks!

**Pull request closed without merging**
